import { Tooltip, TooltipTrigger, TooltipContent, TooltipProvider } from '@/components/ui/tooltip';
import Link from 'next/link';
import React from 'react';

const AboutPage = () => {
  return (
    <div className="max-w-3xl mx-auto px-4 py-8 flex flex-col gap-4" >
      <h1 className="text-4xl font-bold mb-8">About the Bad Boys Podcast</h1>
      <div className="flex flex-col gap-4">
        <h2 className="font-semibold mb-4">The Boys</h2>
        <p className="text-sm text-gray-500">- Generated by AI after reading the transcript for 20241222</p>
        <p>Three friends, Harley (the angry old atheist), <Link className="underline" href="/about/mcp">Tony (aka MCP)</Link>, and Fonso, 
          get together to randomly rant about movies and all their weekends and other nonsense. From reviewing the latest releases to 
          diving into cult classics, nothing is off-limits. Expect irreverent humor, passionate opinions, and plenty of 
          tangents as they navigate the world of film, often disagreeing along the way. With a healthy dose of listener 
          interaction and running gags, "The Bad Boys Podcast" offers a unique and unfiltered take on movies, guaranteed
          to spark debate and entertain.</p>
        <img src="/bad-ghibli-boys.png" alt="Bad Boys" />
      </div>      
      <div className="flex flex-col gap-4">
        <h2 className="text-2xl font-semibold mb-4">The Podcast</h2>
        
        <p>Fonso and Harley met back in &nbsp;
          <TooltipProvider>
            <Tooltip>
              <TooltipTrigger>
                <span className="underline">the olden times</span>
              </TooltipTrigger>
              <TooltipContent>
                <p>1990s</p>
              </TooltipContent>
            </Tooltip>
          </TooltipProvider>
        </p>
        <p>At one point, Harley chose to leave the city life in favor of the the woods</p>
        <p>They would keep in touch through weekly phone calls</p>
        <p>They found that the conversations would always circle back to movies</p>
        <p>So they decided to start recording it and sending the files to their friends!</p>
        <p>...via email. By Harley.</p>
        <p>At one point, MCP received one of these emails</p>
        <p>Being that he was a software developer, he decided to make a website for the podcast</p>
        <p>As "payment" Fonso and Harley let MCP be a guest on one of the episodes</p>
        <p>MCP never stopped being a guest!</p>
        <p>Eventually MCP took over the recording and uploading duties</p>
        <p>A decade later, they're still yelling at each other over movies</p>
      
      </div>
    </div>    
  );
};

export default AboutPage;